version: '3.8'

services:
  db:
    image: postgres:17.5-alpine3.22
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: project-shopping-cart
      POSTGRES_USER: root
      POSTGRES_PASSWORD: master@golang123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: